version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - sd_net
  database:
    image: mariadb:latest
    container_name: db
    ports:
      - 3307:3306
    environment:
      - MARIADB_DATABASE=paperland
      - MARIADB_PORT=3306
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - "./init/master:/docker-entrypoint-initdb.d"
      - "./conf/master:/etc/mysql/conf.d"
      - "./data/master:/var/lib/mysql"
    networks:
      - sd_net
  database-backup:
    image: mariadb:latest
    container_name: db-backup
    environment:
      - MARIADB_MASTER_ROOT_PASSWORD=12345
      - MARIADB_ROOT_PASSWORD=12345
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./init/replica:/docker-entrypoint-initdb.d"
      - "./conf/replica:/etc/mysql/conf.d"
      - "./data/replica:/var/lib/mysql"
    depends_on:
      - database
    networks:
      - sd_net
    links:
      - database
  storage:
    image: minio/minio
    container_name: sd-minio
    ports:
      - 9000:9000
      - 41277:41277
    environment:
      MINIO_ACCESS_KEY: be6b156f1127338b0bc9c6de77279fb5 # generated using node's crypto.randomBytes
      MINIO_SECRET_KEY: 311c8c64ce7ea4d686cb6921ee69eaea # generated using node's crypto.randomBytes
      MINIO_REGION: us-east-2
      MINIO_HTTP_PORT: 9000
    command: minio server /data --console-address 0.0.0.0:41277
    volumes:
      - ./minio-data:/data
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000"
    image: t3-app
    environment:
      - DATABASE_URL=mysql://root:12345@db/paperland
      - NEXTAUTH_URL=http://localhost
    env_file:
      - .env
    networks:
      - sd_net
networks:
  sd_net:
    driver: bridge
volumes:
  data:
    driver: local
  data-backup:
    driver: local
